version: '3.7'

services:

  elasticsearch:

    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.2"

    ports:
      - 9200:9200
      - 9300:9300

    environment:
      - 'discovery.type=single-node'

    container_name: elasticsearch

  es-indexer:

    build:

      context: elasticsearch/indexer
      dockerfile: Dockerfile

    depends_on:
      - elasticsearch

    container_name: es-indexer
