version: '3.7'

services:

  elasticsearch:

    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.8"

    ports:
      - 9200:9200
      - 9300:9300

    environment:
      - 'discovery.type=single-node'

    container_name: elasticsearch

  es-indexer:

    build:

      context: elasticsearch/indexer
      dockerfile: Dockerfile

    depends_on:
      - elasticsearch

    container_name: es-indexer


  cassandra:

    image: "bitnami/cassandra:3.11.8"

    ports:
      - 7000:7000
      - 9042:9042

    environment:
      - CASSANDRA_SEEDS=cassandra

    volumes:
      - ./cassandra/scripts:/docker-entrypoint-initdb.d

    container_name: cassandra

  postgresql:

    image: "postgres:12.4-alpine"

    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=default_db
      - POSTGRES_USER=default_user
      - POSTGRES_PASSWORD=default_pass

    volumes:
      - ./postgresql/scripts:/docker-entrypoint-initdb.d

    container_name: postgresql
